# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Node.js image as a build environment
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the source code
COPY src src

# Build the TypeScript code
RUN npm run build

# Use a smaller image for the final output
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy only the necessary files from the builder
COPY --from=builder /app/build build
COPY package.json package-lock.json ./

# Install only production dependencies
RUN npm install --only=production

# Set environment variables for the server
ENV PENUMBRA_NODE_URL=https://rpc.penumbra.zone \
    PENUMBRA_NETWORK=mainnet \
    PENUMBRA_CHAIN_ID=penumbra-1 \
    PENUMBRA_REQUEST_TIMEOUT=30000 \
    PENUMBRA_REQUEST_RETRIES=5

# Command to run the server
ENTRYPOINT ["node", "build/index.js"]